function h = create_label(text_str, x, y)
    h = uicontrol('Style', 'text', 'String', text_str, ...
        'Position', [x y 60 30], ...
        'BackgroundColor', [0 0 0], ...
        'ForegroundColor', [1 1 1]);
end
